### ISSUE TITLE
snp-eff download make error

### ISSUE THREAD

**Issue by mcnaircm** [gkno/gkno_launcher#69]
So everything has been working smoothly as far as alignment and variant calling up to this point, however, when I try to download the human snpeff database I get a make error.  Here is the code: 

gkno snpeff-download -d human                                                                                                                                                                                               [ 3:37PM]
# 

  University of Utah gkno package

  version:    2.58.0
  date:       June 2016
#   git commit: ee73fde97ca0e649661ceec22f8d35d56880a0d1

Workflow:
   download (snpeff-download):    Download SnpEff database.

Logging gkno usage with ID: snpeff-download...complete.
Executing task: download...make: **\* [/home/cmm024/Tools_Installed/gkno_launcher/tools/snpEff/data/test] Error 255
make: Target `all' not remade because of errors.

I get this error no matter which data base I try to download... I'm not sure if its something that I need to fix on my end, but everything was working fine up until this!

-Chris

**Comment by mcnaircm** [comment]
Here is the contents of snpeff-download.stderr:

 at ca.mcgill.mcb.pcingola.interval.Genome.<init>(Genome.java:102)
        at ca.mcgill.mcb.pcingola.snpEffect.Config.readGenomeConfig(Config.java:594)
        at ca.mcgill.mcb.pcingola.snpEffect.Config.readConfig(Config.java:562)
        at ca.mcgill.mcb.pcingola.snpEffect.Config.init(Config.java:422)
        at ca.mcgill.mcb.pcingola.snpEffect.Config.<init>(Config.java:107)
        at ca.mcgill.mcb.pcingola.snpEffect.commandLine.SnpEff.loadConfig(SnpEff.java:265)
        at ca.mcgill.mcb.pcingola.snpEffect.commandLine.SnpEffCmdDownload.runDownloadGenome(SnpEffCmdDownload.java:79)
        at ca.mcgill.mcb.pcingola.snpEffect.commandLine.SnpEffCmdDownload.run(SnpEffCmdDownload.java:71)
        at ca.mcgill.mcb.pcingola.snpEffect.commandLine.SnpEff.run(SnpEff.java:883)
        at ca.mcgill.mcb.pcingola.snpEffect.commandLine.SnpEff.main(SnpEff.java:128)

I tried to run it twice so there are two different .stderr files and both have the same contents.  Anyway let me know what you think, and if you think that there would be a workaround if it is a firewall issue!

Cheers,
Chris

**Comment by AlistairNWard** [comment]
Oh, sorry, I totally missed this. The error is in your command line. There
is no database with the name 'human'. If you want the database associated
with the human reference genome GRCh37, you need to download the database
GRCh37.75. One reason I am concerned about you not getting resources is
that I've tried to make command lines simpler by ensuring you don't need to
know this information or need to specify commonly used parameters. This is
achieved by using parameter sets. For example, type the command 'gkno
snpeff-download -h' and you get the help information for the pipeline.
Under the pipeline are listed a number of parameter sets. In this case, if
you use the human parameter set 'gkno snpeff-download -ps human -h', you
will see all the parameters that are set by using the 'human' parameter
set. In this case, the only parameter is that --database is set to
GRCh37.75. So try:

gkno snpeff-download -ps human

and you should get the resources you need. In most cases, the parameter
sets will include files associated with a resource bundle, so you would
have to download that with gkno add-resource <resource name>. I'm slowly
changing over 'human' resources to grch37 and grch38 so you can use the two
most commonly used sets of files. Downloading the bundles will give you the
fasta, bwa indexes etc. If you want to use files you already have, you can
create your own personalised parameter sets so you don't have to retype
things on the command line over and over. Let me know if you want to know
more and I'm happy to help.

Let me know if this works.

Al


Alistair Ward, PhD
Director, Research and Science
Department of Human Genetics
USTAR Center for Genetic Discovery
Eccles Institute of Human Genetics
University of Utah School of Medicine​
15 North 2030 East, Room 7140
Salt Lake City, UT 84112-5330

Co-founder, Frameshift labs, LLC

**Comment by mcnaircm** [comment]
Great that worked perfectly!  So just to clarify as of now you can only download one package through gkno and that is for grch37.75, unless I used gkno add-resource for grch37 or 38?

**Comment by AlistairNWard** [comment]
No, you can download as many packages as you like. Using gkno add-resource
will download resource bundles containing lots of files for those
resources. So if you added the GRCh37 gkno resource, it would download the
reference fasta, all the bwa index files so you can start aligning
immediately etc. It doesn't have any snpEff files in it. But, if you type
gkno update-light, this will update gkno to the latest version. The 'light'
part means it updates only the configuration files that define tools and
pipelines. 'gkno update' will also update all of the tools themselves which
will take a lot longer and they don't usually have any updates. If you
update, then type:

gkno snpeff-databases

This will create a file called snpEff_databases.txt, which contains a list
of all the databases that can be downloaded for use with snpeff. You can
then download any of these using:

gkno snpeff-download --database <NAME>

If you want the GRCh38 database, you can use:

gkno snpeff-download -ps grch38

You have to do the update first though, since I just added the GRCh38
parameter set and databases pipeline. Hope this helps,

Al


Alistair Ward, PhD
Director, Research and Science
Department of Human Genetics
USTAR Center for Genetic Discovery
Eccles Institute of Human Genetics
University of Utah School of Medicine​
15 North 2030 East, Room 7140
Salt Lake City, UT 84112-5330

Co-founder, Frameshift labs, LLC

**Comment by AlistairNWard** [comment]
Hey Chris,

Just wanted to check in to see if gkno is working for you and if you are
finding it useful? If there are any things that you were hoping to achieve
that it isn't really helping with? Feedback is always appreciated to help
support the project!

Al


Alistair Ward, PhD
Director, Research and Science
Department of Human Genetics
USTAR Center for Genetic Discovery
Eccles Institute of Human Genetics
University of Utah School of Medicine​
15 North 2030 East, Room 7140
Salt Lake City, UT 84112-5330

Co-founder, Frameshift labs, LLC

**Comment by mcnaircm** [comment]
Hey Al,
Sorry for the super delayed response, I had been working on some other projects and completely forgot to get back to you!  Anyway, everything seemed to work find after working through some initial issues, as far as alignment is concerned.  What would be helpful though would be multiple variant annotation tools (other than just snpeff).  It might also be cool to have a variant caller comparison tool (similar to what you guys have in demo on iobio).  Anyway, I'm sure both of those things are no easy task but figured I'd suggest them nonetheless!  Thanks again for all the help thusfar!
